<?xml version="1.0" encoding="utf-8"?><Database Name="MANOFR" Class="ManofrSqlDbModelDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.;Initial Catalog=MANOFR;Persist Security Info=True;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="MANOFRConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ApplicationsTypes" Member="ApplicationsTypes">
    <Type Name="ApplicationsType">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Type" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Association Name="ApplicationsType_Project" Member="Projects" ThisKey="ID" OtherKey="SystemType" Type="Project" />
    </Type>
  </Table>
  <Table Name="dbo.ComponentsStatus" Member="ComponentsStatus">
    <Type Name="ComponentsStatus">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Association Name="ComponentsStatus_Project" Member="Projects" ThisKey="ID" OtherKey="Status" Type="Project" />
      <Association Name="ComponentsStatus_Sprint" Member="Sprints" ThisKey="ID" OtherKey="Status" Type="Sprint" />
      <Association Name="ComponentsStatus_Task" Member="Tasks" ThisKey="ID" OtherKey="Status" Type="Task" />
      <Association Name="ComponentsStatus_UserStory" Member="UserStories" ThisKey="ID" OtherKey="StatusID" Type="UserStory" />
    </Type>
  </Table>
  <Table Name="dbo.Domains" Member="Domains">
    <Type Name="Domain">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Domain" Member="Domain1" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Association Name="Domain_Module" Member="Modules" ThisKey="ID" OtherKey="Domain" Type="Module" />
      <Association Name="Domain_Project" Member="Projects" ThisKey="ID" OtherKey="Domain" Type="Project" />
    </Type>
  </Table>
  <Table Name="dbo.Modules" Member="Modules">
    <Type Name="Module">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Module" Member="Module1" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Domain" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Module_ProjectsModule" Member="ProjectsModules" ThisKey="ID" OtherKey="Module" Type="ProjectsModule" />
      <Association Name="Module_UserStory" Member="UserStories" ThisKey="ID" OtherKey="ModuleID" Type="UserStory" />
      <Association Name="Module_Epic" Member="Epics" ThisKey="ID" OtherKey="Module" Type="Epic" />
      <Association Name="Domain_Module" Member="Domain1" ThisKey="Domain" OtherKey="ID" Type="Domain" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Projects" Member="Projects">
    <Type Name="Project">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(300) NOT NULL" CanBeNull="false" />
      <Column Name="Domain" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SystemType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CustomerName" Type="System.String" DbType="NVarChar(400)" CanBeNull="true" />
      <Column Name="CustomerPhone" Type="System.String" DbType="NVarChar(400)" CanBeNull="true" />
      <Column Name="CustomerEmail" Type="System.String" DbType="NVarChar(400)" CanBeNull="true" />
      <Column Name="StartDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="EndDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CreationDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="CreatedBy" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="isSuspended" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Project_ProjectsModule" Member="ProjectsModules" ThisKey="ID" OtherKey="Project" Type="ProjectsModule" />
      <Association Name="Project_ProjectsNFR" Member="ProjectsNFRs" ThisKey="ID" OtherKey="ProjectID" Type="ProjectsNFR" />
      <Association Name="Project_ProjectsUser" Member="ProjectsUsers" ThisKey="ID" OtherKey="Project" Type="ProjectsUser" />
      <Association Name="Project_Sprint" Member="Sprints" ThisKey="ID" OtherKey="ProjectID" Type="Sprint" />
      <Association Name="Project_Task" Member="Tasks" ThisKey="ID" OtherKey="ProjectID" Type="Task" />
      <Association Name="Project_UserStory" Member="UserStories" ThisKey="ID" OtherKey="ProjectID" Type="UserStory" />
      <Association Name="Project_Epic" Member="Epics" ThisKey="ID" OtherKey="ProjectID" Type="Epic" />
      <Association Name="Domain_Project" Member="Domain1" ThisKey="Domain" OtherKey="ID" Type="Domain" IsForeignKey="true" />
      <Association Name="ComponentsStatus_Project" Member="ComponentsStatus" ThisKey="Status" OtherKey="ID" Type="ComponentsStatus" IsForeignKey="true" />
      <Association Name="ApplicationsType_Project" Member="ApplicationsType" ThisKey="SystemType" OtherKey="ID" Type="ApplicationsType" IsForeignKey="true" />
      <Association Name="User_Project" Member="User" ThisKey="CreatedBy" OtherKey="ID" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ProjectsModules" Member="ProjectsModules">
    <Type Name="ProjectsModule">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Project" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Module" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Module_ProjectsModule" Member="Module1" ThisKey="Module" OtherKey="ID" Type="Module" IsForeignKey="true" />
      <Association Name="Project_ProjectsModule" Member="Project1" ThisKey="Project" OtherKey="ID" Type="Project" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ProjectsNFRs" Member="ProjectsNFRs">
    <Type Name="ProjectsNFR">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProjectID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NFR" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="ProjectsNFR_UserStory" Member="UserStories" ThisKey="ID" OtherKey="NFR_NFRID" Type="UserStory" />
      <Association Name="Project_ProjectsNFR" Member="Project" ThisKey="ProjectID" OtherKey="ID" Type="Project" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ProjectsUsers" Member="ProjectsUsers">
    <Type Name="ProjectsUser">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Project" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SysUser" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Project_ProjectsUser" Member="Project1" ThisKey="Project" OtherKey="ID" Type="Project" IsForeignKey="true" />
      <Association Name="User_ProjectsUser" Member="User" ThisKey="SysUser" OtherKey="ID" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Sprints" Member="Sprints">
    <Type Name="Sprint">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProjectID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(300) NOT NULL" CanBeNull="false" />
      <Column Name="StartDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="EndDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Goal" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreationDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="CreatedBy" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Sprint_UserStory" Member="UserStories" ThisKey="ID" OtherKey="SprintID" Type="UserStory" />
      <Association Name="Project_Sprint" Member="Project" ThisKey="ProjectID" OtherKey="ID" Type="Project" IsForeignKey="true" />
      <Association Name="ComponentsStatus_Sprint" Member="ComponentsStatus" ThisKey="Status" OtherKey="ID" Type="ComponentsStatus" IsForeignKey="true" />
      <Association Name="User_Sprint" Member="User" ThisKey="CreatedBy" OtherKey="ID" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SystemNFRs" Member="SystemNFRs">
    <Type Name="SystemNFR">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NFR" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Tasks" Member="Tasks">
    <Type Name="Task">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProjectID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Priority" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AssignedUserStory" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RequirementType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AttachmentUrl" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreationDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="UpdatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LastUpdateDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="Task_Tasks_Assigned_User" Member="Tasks_Assigned_Users" ThisKey="ID" OtherKey="TaskID" Type="Tasks_Assigned_User" />
      <Association Name="Project_Task" Member="Project" ThisKey="ProjectID" OtherKey="ID" Type="Project" IsForeignKey="true" />
      <Association Name="ComponentsStatus_Task" Member="ComponentsStatus" ThisKey="Status" OtherKey="ID" Type="ComponentsStatus" IsForeignKey="true" />
      <Association Name="US_Priority_Task" Member="US_Priority" ThisKey="Priority" OtherKey="ID" Type="US_Priority" IsForeignKey="true" />
      <Association Name="US_Requirement_Type_Task" Member="US_Requirement_Type" ThisKey="RequirementType" OtherKey="ID" Type="US_Requirement_Type" IsForeignKey="true" />
      <Association Name="User_Task" Member="User" ThisKey="CreatedBy" OtherKey="ID" Type="User" IsForeignKey="true" />
      <Association Name="User_Task1" Member="User1" ThisKey="UpdatedBy" OtherKey="ID" Type="User" IsForeignKey="true" />
      <Association Name="UserStory_Task" Member="UserStory" ThisKey="AssignedUserStory" OtherKey="ID" Type="UserStory" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tasks_Assigned_Users" Member="Tasks_Assigned_Users">
    <Type Name="Tasks_Assigned_User">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TaskID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AssignedUser" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Task_Tasks_Assigned_User" Member="Task" ThisKey="TaskID" OtherKey="ID" Type="Task" IsForeignKey="true" />
      <Association Name="User_Tasks_Assigned_User" Member="User" ThisKey="AssignedUser" OtherKey="ID" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.US_Positivity" Member="US_Positivities">
    <Type Name="US_Positivity">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PosNeg_Value" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Association Name="US_Positivity_UserStory" Member="UserStories" ThisKey="ID" OtherKey="NFR_PosOrNeg" Type="UserStory" />
    </Type>
  </Table>
  <Table Name="dbo.US_Priorities" Member="US_Priorities">
    <Type Name="US_Priority">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Priority_Value" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Association Name="US_Priority_Task" Member="Tasks" ThisKey="ID" OtherKey="Priority" Type="Task" />
      <Association Name="US_Priority_UserStory" Member="UserStories" ThisKey="ID" OtherKey="UsPriority" Type="UserStory" />
    </Type>
  </Table>
  <Table Name="dbo.US_Relations" Member="US_Relations">
    <Type Name="US_Relation">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Relation_Value" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Req_Type" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="US_Relation_UserStory" Member="UserStories" ThisKey="ID" OtherKey="RelatedTo" Type="UserStory" />
    </Type>
  </Table>
  <Table Name="dbo.US_Requirement_Types" Member="US_Requirement_Types">
    <Type Name="US_Requirement_Type">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Type_Value" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Association Name="US_Requirement_Type_Task" Member="Tasks" ThisKey="ID" OtherKey="RequirementType" Type="Task" />
      <Association Name="US_Requirement_Type_UserStory" Member="UserStories" ThisKey="ID" OtherKey="RequirementType" Type="UserStory" />
    </Type>
  </Table>
  <Table Name="dbo.US_Types" Member="US_Types">
    <Type Name="US_Type">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Type_Value" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Association Name="US_Type_UserStory" Member="UserStories" ThisKey="ID" OtherKey="UsType" Type="UserStory" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Fullname" Type="System.String" DbType="NVarChar(400)" CanBeNull="true" />
      <Column Name="Title" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FirstTimeLogin" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="User_Project" Member="Projects" ThisKey="ID" OtherKey="CreatedBy" Type="Project" />
      <Association Name="User_ProjectsUser" Member="ProjectsUsers" ThisKey="ID" OtherKey="SysUser" Type="ProjectsUser" />
      <Association Name="User_Sprint" Member="Sprints" ThisKey="ID" OtherKey="CreatedBy" Type="Sprint" />
      <Association Name="User_Task" Member="Tasks" ThisKey="ID" OtherKey="CreatedBy" Type="Task" />
      <Association Name="User_Task1" Member="Tasks1" ThisKey="ID" OtherKey="UpdatedBy" Type="Task" />
      <Association Name="User_Tasks_Assigned_User" Member="Tasks_Assigned_Users" ThisKey="ID" OtherKey="AssignedUser" Type="Tasks_Assigned_User" />
      <Association Name="User_UserStory" Member="UserStories" ThisKey="ID" OtherKey="CreatedBy" Type="UserStory" />
      <Association Name="User_UserStory1" Member="UserStories1" ThisKey="ID" OtherKey="UpdatedBy" Type="UserStory" />
      <Association Name="User_UserStory_Assigned_User" Member="UserStory_Assigned_Users" ThisKey="ID" OtherKey="AssignedUser" Type="UserStory_Assigned_User" />
      <Association Name="UsersTitle_User" Member="UsersTitle" ThisKey="Title" OtherKey="ID" Type="UsersTitle" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.UsersNFRs" Member="UsersNFRs">
    <Type Name="UsersNFR">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NFR" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.UsersTitles" Member="UsersTitles">
    <Type Name="UsersTitle">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Association Name="UsersTitle_User" Member="Users" ThisKey="ID" OtherKey="Title" Type="User" />
    </Type>
  </Table>
  <Table Name="dbo.UserStories" Member="UserStories">
    <Type Name="UserStory">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProjectID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SprintID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EpicID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModuleID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StatusID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UsType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RequirementType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RelatedTo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UsPriority" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AttachmentsUrl" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="FRC_CustomUserStory" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="FRS_Title" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="FRS_AsA" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="FRS_SoThat" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="FRS_IWish" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="FRS_AcceptanceCriteria" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NFR_PosOrNeg" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NFR_NFRID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NFR_Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CreationDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="CreatedBy" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LastUpdateDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="UpdatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NFR_For" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NFR_IWant" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NFR_ToBe" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="UserStory_Task" Member="Tasks" ThisKey="ID" OtherKey="AssignedUserStory" Type="Task" />
      <Association Name="UserStory_UserStory_Assigned_User" Member="UserStory_Assigned_Users" ThisKey="ID" OtherKey="UserStory" Type="UserStory_Assigned_User" />
      <Association Name="UserStory_UserStory_Related_Story" Member="UserStory_Related_Stories" ThisKey="ID" OtherKey="RelatedToStory" Type="UserStory_Related_Story" />
      <Association Name="UserStory_UserStory_Related_Story1" Member="UserStory_Related_Stories1" ThisKey="ID" OtherKey="UserStory" Type="UserStory_Related_Story" />
      <Association Name="User_UserStory" Member="User" ThisKey="CreatedBy" OtherKey="ID" Type="User" IsForeignKey="true" />
      <Association Name="Module_UserStory" Member="Module" ThisKey="ModuleID" OtherKey="ID" Type="Module" IsForeignKey="true" />
      <Association Name="ProjectsNFR_UserStory" Member="ProjectsNFR" ThisKey="NFR_NFRID" OtherKey="ID" Type="ProjectsNFR" IsForeignKey="true" />
      <Association Name="US_Positivity_UserStory" Member="US_Positivity" ThisKey="NFR_PosOrNeg" OtherKey="ID" Type="US_Positivity" IsForeignKey="true" />
      <Association Name="Project_UserStory" Member="Project" ThisKey="ProjectID" OtherKey="ID" Type="Project" IsForeignKey="true" />
      <Association Name="US_Relation_UserStory" Member="US_Relation" ThisKey="RelatedTo" OtherKey="ID" Type="US_Relation" IsForeignKey="true" />
      <Association Name="US_Requirement_Type_UserStory" Member="US_Requirement_Type" ThisKey="RequirementType" OtherKey="ID" Type="US_Requirement_Type" IsForeignKey="true" />
      <Association Name="Sprint_UserStory" Member="Sprint" ThisKey="SprintID" OtherKey="ID" Type="Sprint" IsForeignKey="true" />
      <Association Name="ComponentsStatus_UserStory" Member="ComponentsStatus" ThisKey="StatusID" OtherKey="ID" Type="ComponentsStatus" IsForeignKey="true" />
      <Association Name="User_UserStory1" Member="User1" ThisKey="UpdatedBy" OtherKey="ID" Type="User" IsForeignKey="true" />
      <Association Name="US_Priority_UserStory" Member="US_Priority" ThisKey="UsPriority" OtherKey="ID" Type="US_Priority" IsForeignKey="true" />
      <Association Name="US_Type_UserStory" Member="US_Type" ThisKey="UsType" OtherKey="ID" Type="US_Type" IsForeignKey="true" />
      <Association Name="Epic_UserStory" Member="Epic" ThisKey="EpicID" OtherKey="ID" Type="Epic" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.UserStory_Assigned_Users" Member="UserStory_Assigned_Users">
    <Type Name="UserStory_Assigned_User">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserStory" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AssignedUser" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="User_UserStory_Assigned_User" Member="User" ThisKey="AssignedUser" OtherKey="ID" Type="User" IsForeignKey="true" />
      <Association Name="UserStory_UserStory_Assigned_User" Member="UserStory1" ThisKey="UserStory" OtherKey="ID" Type="UserStory" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.UserStory_Related_Stories" Member="UserStory_Related_Stories">
    <Type Name="UserStory_Related_Story">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserStory" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RelatedToStory" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="UserStory_UserStory_Related_Story" Member="UserStory1" ThisKey="RelatedToStory" OtherKey="ID" Type="UserStory" IsForeignKey="true" />
      <Association Name="UserStory_UserStory_Related_Story1" Member="UserStory2" ThisKey="UserStory" OtherKey="ID" Type="UserStory" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.NFR_Rec_AppType" Member="NFR_Rec_AppTypes">
    <Type Name="NFR_Rec_AppType">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AppType" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Reccomended_NFRs" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.NFR_Rec_Domain" Member="NFR_Rec_Domains">
    <Type Name="NFR_Rec_Domain">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Domain" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Reccomended_NFRs" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Epics" Member="Epics">
    <Type Name="Epic">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProjectID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(300) NOT NULL" CanBeNull="false" />
      <Column Name="Module" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Epic_UserStory" Member="UserStories" ThisKey="ID" OtherKey="EpicID" Type="UserStory" />
      <Association Name="Module_Epic" Member="Module1" ThisKey="Module" OtherKey="ID" Type="Module" IsForeignKey="true" />
      <Association Name="Project_Epic" Member="Project" ThisKey="ProjectID" OtherKey="ID" Type="Project" IsForeignKey="true" />
    </Type>
  </Table>
</Database>